[package]
name = "haybale"
version = "0.1.0"
authors = ["Craig Disselkoen <craigdissel@gmail.com>"]
edition = "2018"

[dependencies]
llvm-ir = { git = "https://github.com/cdisselkoen/llvm-ir" }
z3 = { path = "../z3.rs/z3" }
either = "1.5.2"
itertools = "0.8.0"
reduce = "0.1"
log = "0.4.0"
env_logger = "0.6.1"
