[package]
name = "haybale"
version = "0.3.2"
authors = ["Craig Disselkoen <craigdissel@gmail.com>"]
edition = "2018"
description = "Symbolic execution of LLVM IR, written in Rust"
documentation = "https://PLSysSec.github.io/haybale"
repository = "https://github.com/PLSysSec/haybale"
readme = "README.md"
keywords = ["symbolic", "llvm", "IR", "SMT"]
license = "MIT"

[dependencies]
llvm-ir = "0.5.1"
boolector = "0.3.0"
either = "1.5.3"
itertools = "0.8.2"
reduce = "0.1"
cpp_demangle = "0.2"
rustc-demangle = "0.1"
log = { version = "0.4.8", features = ["max_level_debug", "release_max_level_info"] }

[dev-dependencies]
env_logger = "0.6.2"
