[package]
name = "haybale"
version = "0.1.0"
authors = ["Craig Disselkoen <craigdissel@gmail.com>"]
edition = "2018"

[dependencies]
llvm-ir = { git = "https://github.com/cdisselkoen/llvm-ir" }
boolector = { path = "../boolector-rs" }
crossbeam-utils = "0.6.6"
either = "1.5.2"
itertools = "0.8.0"
reduce = "0.1"
log = { version = "0.4.0", features = ["max_level_debug", "release_max_level_info"] }
env_logger = "0.6.1"
