[package]
name = "pitchfork-rs"
version = "0.1.0"
authors = ["Craig Disselkoen <craigdissel@gmail.com>"]
edition = "2018"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm7-0" }

# override the git dependency with our locally-patched version, for now
# see https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#overriding-dependencies
[patch."https://github.com/TheDan64/inkwell"]
inkwell = { path = "../inkwell" }
