[package]
name = "haybale"
version = "0.1.1"
authors = ["Craig Disselkoen <craigdissel@gmail.com>"]
edition = "2018"
description = "Symbolic execution of LLVM IR, written in Rust"
documentation = "https://PLSysSec.github.io/haybale"
repository = "https://github.com/PLSysSec/haybale"
readme = "README.md"
keywords = ["symbolic", "llvm", "IR", "SMT"]
license = "MIT"

[dependencies]
llvm-ir = "0.3.2"
boolector = "0.1.2"
either = "1.5.3"
itertools = "0.8.2"
reduce = "0.1"
log = { version = "0.4.8", features = ["max_level_debug", "release_max_level_info"] }
env_logger = "0.6.2"
